### ISSUE TITLE
Connect error with /var/osquery/osquery.em file

### ISSUE THREAD

**Issue by amiceli** [sidorares/osquery-node#4]
Hello,

When I launch following code : 

```
    let os = osquery.createClient();
    os.query('SELECT uid, name FROM listening_ports l, processes p WHERE l.pid=p.pid', function(err, res) {
        res.json(res);
    });
```

It return an error : 

**Uncaught Error: connect ECONNREFUSED /var/osquery/osquery.em**

Thanks for your help

**Comment by sidorares** [comment]
what's your os? I haven't used this library for quite a while, would you be able to help debugging in case the file location changed?

**Comment by amiceli** [comment]
I'm on a ubuntu base OS : kde neon, 16.04 I htink.
At start `osquery.em` file was missing, I created it (empty file).

Does it need special permission ?

**Comment by sidorares** [comment]
it's created by osquery, and it's unix domain socket

**Comment by datesss** [comment]
so in shell run `osqueryi`, and then run this query:
osquery> select path from osquery_extensions;
+-------------------------------------+
| path                                |
+-------------------------------------+
| /Users/USERNAME/.osquery/shell.em   |
+-------------------------------------+

now you can put that in the args of your node code:
`var os = osquery.createClient({path: '/Users/USERNAME/.osquery/shell.em'});`

the thing that confused me at first is that you need to keep an osqueryi process running for node to connect to it! doy :-P

Thinking about making a pull request that sets this as the default connection string :)
